config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'  
  } 

  devise_scope :user do
    get 'users/sign_up/new_phone' => 'users/registrations#new_phone'
    get 'users/sign_up/sns' => 'users/registrations#sns'
    post 'users/sign_up/' => 'users/registrations#create'
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
  end

  # root画面
  root 'display_items#index'
  # ユーザー新規作成系のルーティング(※暫定！)
  resources :users do
    collection do
      get    :new_info #会員情報入力画面
      post   :create_info #処理
      get    :new_phone #電話番号入力画面
      post   :create_phone #処理
      get    :new_address #住所入力画面
      post   :create_address #処理
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
      get    :complete #完了画面
    end
  end
  # マイページのルーティング
  resources :mypages, only: [:index] do
    collection do
      get    :logout #ログアウト画面
      get    :display_items #出品中画面
      get    :trading_items #取引中画面
      get    :finished_items #売却済み画面
    end
  end
  # ニックネーム&紹介文の編集
  resources :user_nicknames, only: [:edit, :update]
  # 会員情報の編集
  resources :user_profiles, only: [:edit, :update]
  # クレジットカードの編集
  resources :credit_cards do
    collection do
      post 'buy'
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
    end
  end
  # 住所の編集
  resources :addresses,only: [:edit, :update]

  # 出品中-商品のルーティング
  resources :display_items do
    member do
      get :buy #購入画面
    end
    # コメントのルーティング(display_itemsとネスト)
    resources :comments, only: [:create, :destroy]
  end
  # 取引中-商品のルーティング
  resources :trading_items, only: [:create]
  # 出品停止中-商品のルーティング
  resources :stopping_items, only: [:create, :destroy]

  # イメージのルーティング
  resources :images, only: [:index] do
    collection do
      delete  :edit_destroy #編集ページの削除機能
    end
  end
  # カテゴリのルーティング
  resources :categories, only: [:index] do
    collection do
      post  :search_level1 #出品ページの検索、カテゴリ階層2
      post  :search_level2 #出品ページの検索、カテゴリ階層3
    end
  end
  # サイズのルーティング
  resources :sizes, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end
  # ブランドのルーティング
  resources :brands, only: [:index] do
    collection do
      post  :enter #ブランドボックスの作成チェック
      post  :search #出品ページの検索
    end
  end
  # 配送方法のルーティング
  resources :delivery_methods, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def index
  end

  def show
    if @card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_information = customer.cards.retrieve(@card.card_id)

      # 登録しているカード会社のブランドアイコンを表示する
      @card_brand = @card_information.brand      
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def new
    gon.payjp_key = ENV["PAYJP_PRIVATE_KEY"]
    card = CreditCard.find_by(user_id: current_user.id)
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to new_credit_card_path
    else
      customer = Payjp::Customer.create(
        description: '登録テスト',
        card: params['payjp-token'],
        metadata:{user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id,customer_id:customer.id ,card_id: customer.default_card)
      if @card.save
        redirect_to root_path
      else
        redirect_to action: "create"
      end
    end
  end

  def new_credit
    gon.payjp_key = ENV["PAYJP_PRIVATE_KEY"]
    card = CreditCard.find_by(user_id: current_user.id)
  end

  def create_credit
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to new_credit_credit_cards_path
    else
      customer = Payjp::Customer.create(
        description: '登録テスト',
        card: params['payjp-token'],
        metadata:{user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id,customer_id:customer.id ,card_id: customer.default_card)
      if @card.save
        redirect_to complete_users_path
      else
        redirect_to action: "create"
      end
    end
  end

  def buy
    
    card = CreditCard.find_by(user_id: current_user.id)
    @display_item = DisplayItem.find(params[:trading_item][:display_item_id])
    @address = Address.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      if Payjp::Charge.create(
        amount: @display_item.price,
        customer: card.customer_id,
        currency: 'jpy',
        )
        
        
        @trading_item = TradingItem.new(trading_item_params)
        if @trading_item.save
          redirect_to root_path
        end
      end
    end
  end

  def destroy
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)

    #削除に成功した時にポップアップを表示します。
    if @card.destroy 
      customer.delete
      redirect_to mypages_path
    else #削除に失敗した時にアラートを表示します。
      redirect_to action: "show", alert: "削除できませんでした"
    end
  end



  private

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.where(user_id: current_user.id).present?
  end

  def trading_item_params
    params.require(:trading_item).permit(:user_id, :display_item_id)
  end
end

app/views/credit_cards/index.html.haml
= render 'shared/header'

- breadcrumb :credit_card
%nav.bread-crumbs
  %ul
    %li
      = breadcrumbs separator: " #{content_tag(:i, '', class: 'fa fa-angle-right')} "

.mypage-clearfix
  .mypage

    = render 'shared/side-bar'

    .credit
      .credit__whole
        .credit__whole__content
          .credit__whole__content__headder
            支払い方法
          .credit__whole__content__footer
            .credit__whole__content__footer__card-list
              .credit__whole__content__footer__card-list__title
                クレジットカード一覧
            .credit__whole__content__footer__add-card
              %section.credit__whole__content__footer__add-card__inside
                = link_to new_credit_card_path, class:'red-submit-button' ,data:{turbolinks:"false"}do
                  = image_tag ""
                  =fa_icon "credit-card",class: '.card'
                  クレジッドカードを追加する
                  
            .credit__whole__content__footer__warning-note
              =link_to "#",class:'how-to-pay' do
                支払い方法について
                =fa_icon "chevron-right",class: '.profile-form__text-link__right__icon'


= render 'shared/sell-icon'
= render 'shared/aside'
= render 'shared/footer'

app/views/credit_cards/new.html.haml
= render 'shared/header'

- breadcrumb :credit_card_input
%nav.bread-crumbs
  %ul
    %li
      = breadcrumbs separator: " #{content_tag(:i, '', class: 'fa fa-angle-right')} "

.mypage-clearfix
  .mypage
    = render 'shared/side-bar'

    .credit
      .credit__whole
        .newinfo-content__mono-content
          .newinfo-content__mono-content__head-edit
            クレジットカード情報入力
          .newinfo-content__mono-content__space
            = form_tag(credit_cards_path,method: :post,name: "inputForm") do
              .field-first-edit
                %label  カード番号
                %span.required-icon 必須
                =text_field_tag "number", "",  placeholder: "半角数字のみ",class:'input',maxlength: "16", type: "text",id: "payment_card_no",name:"number"
              .field-icon-edit
                .credit-icon
                
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615", size: "49x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3466462615", size: "34x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3466462615", size: "30x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3466462615", size: "32x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3466462615", size: "21x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3466462615", size: "32x20"
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?346646261", size: "32x20"
              .field-second-edit
                %label 有効期限
                %span.required-icon 必須
                %br
                .select-wrap-half
                  %select#card_expire_mm.credit-cards-select{name: "exp_month", type: "text"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %i.arrow-icon-credit  
                  %span.option-text 月
                .select-wrap-half
                  %select#card_expire_yy.credit-cards-select{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %span.option-text 年

              .field-second-edit
                %label.form-label セキュリティコード
                %span.required-icon 必須
                = text_field_tag "cvc", "", class: "input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc_code",name:"number",type:"text"
                #card_token
                .credit-notice
                  = fa_icon "question-circle"
                  カード裏面の番号とは？
              .field-second-edit
                = submit_tag "追加する", id: "token_submit", class: 'next-btn'

= render 'shared/sell-icon'
= render 'shared/aside'
= render 'shared/footer'

app/views/credit_cards/new_credit.html.haml
.newcredit-content
  .newcredit-content__mono-header
    = link_to root_path do
      =image_tag"logo.svg",class: 'newcredit-content__mono-header__logo'
  .newcredit-content__mono-header__situation
    .newcredit-content__mono-header__situation__bar
      .newcredit-content__mono-header__situation__bar__info 
        .newcredit-content__mono-header__situation__bar__info__text 会員情報
        .newcredit-content__mono-header__situation__bar__info__dot
        .newcredit-content__mono-header__situation__bar__info__line
      .newcredit-content__mono-header__situation__bar__tel
        .newcredit-content__mono-header__situation__bar__tel__text 電話番号認証
        .newcredit-content__mono-header__situation__bar__tel__dot
        .newcredit-content__mono-header__situation__bar__tel__line
      .newcredit-content__mono-header__situation__bar__address
        .newcredit-content__mono-header__situation__bar__address__text お届け先住所入力
        .newcredit-content__mono-header__situation__bar__address__dot
        .newcredit-content__mono-header__situation__bar__address__line
      .newcredit-content__mono-header__situation__bar__pay
        .newcredit-content__mono-header__situation__bar__pay__text 支払い方法
        .newcredit-content__mono-header__situation__bar__pay__dot
        .newcredit-content__mono-header__situation__bar__pay__line
      .newcredit-content__mono-header__situation__bar__finished 
        .newcredit-content__mono-header__situation__bar__finished__text 完了
        .newcredit-content__mono-header__situation__bar__finished__dot
        .newcredit-content__mono-header__situation__bar__finished__line
  .newinfo-content__mono-content
    .newinfo-content__mono-content__head お支払い方法
    .newinfo-content__mono-content__space
      = form_tag(create_credit_credit_cards_path,method: :post,name: "inputForm") do
        .field
          %label  カード番号
          %span.required-icon 
            必須
          =text_field_tag "number", "",  placeholder: "半角数字のみ",class:'input',maxlength: "16", type: "text",id: "payment_card_no",name:"number"
        .field-second
          .credit-icon
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615", size: "49x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3466462615", size: "34x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3466462615", size: "30x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3466462615", size: "32x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3466462615", size: "21x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3466462615", size: "32x20"
            = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?346646261", size: "32x20"
        .field-first
          %label 有効期限
          %span.required-icon 
            必須
          %br
          %select#card_expire_mm.timetextfield{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月
        .field-first
          %select#card_expire_yy.timetextfield{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
        .field
          %label.form-label セキュリティコード
          %span.required-icon 必須
          = text_field_tag "cvc", "", class: "input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc_code",name:"number",type:"text"
          #card_token
          .credit-notice
            = fa_icon "question-circle"
            カード裏面の番号とは？
        .field-second-edit
          = submit_tag "次に進む", id: "token_submit", class: 'next-btn'

= render 'shared/afooter'

app/views/credit_cards/show.html.haml
= render 'shared/header'

- breadcrumb :credit_card
%nav.bread-crumbs
  %ul
    %li
      = breadcrumbs separator: " #{content_tag(:i, '', class: 'fa fa-angle-right')} "

.mypage-clearfix
  .mypage

    = render 'shared/side-bar'

    .credit
      .credit__whole
        .credit__whole__content
          .credit__whole__content__headder
            支払い方法
          .credit__whole__content__footer
            .credit__whole__content__footer__card-list
              .credit__whole__content__footer__card-list__title
                クレジットカード一覧
            .credit__whole__content__footer__add-card
              %section.credit__whole__content__footer__add-card__inside
                %figure
                  = image_tag "http://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615", size: "49x20" ,alt: @card_brand, id: "card_image"
                .credit__whole__content__footer__add-card__inside__info
                  ="************" + "#{@default_card_information.last4}"
                .credit__whole__content__footer__add-card__inside__info
                  - exp_month = "#{@default_card_information.exp_month.to_s}"
                  - exp_year = "#{@default_card_information.exp_year.to_s.slice(2,3)}"
                  = exp_month + " / " + "#{exp_year}"
                =link_to credit_card_path(current_user.credit_card) ,method: :delete,class:'credit__whole__content__footer__add-card__inside__remove' do
                  削除する
                  
            .credit__whole__content__footer__warning-note
              =link_to "#",class:'how-to-pay' do
                支払い方法について
                =fa_icon "chevron-right",class: '.profile-form__text-link__right__icon'


= render 'shared/sell-icon'
= render 'shared/aside'
= render 'shared/footer'