config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'  
  } 

  devise_scope :user do
    get 'users/sign_up/new_phone' => 'users/registrations#new_phone'
    get 'users/sign_up/sns' => 'users/registrations#sns'
    post 'users/sign_up/' => 'users/registrations#create'
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
  end

  # root画面
  root 'display_items#index'
  # ユーザー新規作成系のルーティング(※暫定！)
  resources :users do
    collection do
      get    :new_info #会員情報入力画面
      post   :create_info #処理
      get    :new_phone #電話番号入力画面
      post   :create_phone #処理
      get    :new_address #住所入力画面
      post   :create_address #処理
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
      get    :complete #完了画面
    end
  end
  # マイページのルーティング
  resources :mypages, only: [:index] do
    collection do
      get    :logout #ログアウト画面
      get    :display_items #出品中画面
      get    :trading_items #取引中画面
      get    :finished_items #売却済み画面
    end
  end
  # ニックネーム&紹介文の編集
  resources :user_nicknames, only: [:edit, :update]
  # 会員情報の編集
  resources :user_profiles, only: [:edit, :update]
  # クレジットカードの編集
  resources :credit_cards do
    collection do
      post 'buy'
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
    end
  end
  # 住所の編集
  resources :addresses,only: [:edit, :update]

  # 出品中-商品のルーティング
  resources :display_items do
    member do
      get :buy #購入画面
    end
    # コメントのルーティング(display_itemsとネスト)
    resources :comments, only: [:create, :destroy]
  end
  # 取引中-商品のルーティング
  resources :trading_items, only: [:create]
  # 出品停止中-商品のルーティング
  resources :stopping_items, only: [:create, :destroy]

  # イメージのルーティング
  resources :images, only: [:index] do
    collection do
      delete  :edit_destroy #編集ページの削除機能
    end
  end
  # カテゴリのルーティング
  resources :categories, only: [:index] do
    collection do
      post  :search_level1 #出品ページの検索、カテゴリ階層2
      post  :search_level2 #出品ページの検索、カテゴリ階層3
    end
  end
  # サイズのルーティング
  resources :sizes, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end
  # ブランドのルーティング
  resources :brands, only: [:index] do
    collection do
      post  :enter #ブランドボックスの作成チェック
      post  :search #出品ページの検索
    end
  end
  # 配送方法のルーティング
  resources :delivery_methods, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: %i[facebook google_oauth2]

  has_one :address, dependent: :destroy

  has_many :display_items, dependent: :delete_all
  has_many :trading_items, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :sns_credentials, dependent: :destroy
  has_one :credit_card, dependent: :destroy


  validates :nickname, presence: true
  validates :email, presence: true, uniqueness:true
  validates :password, confirmation: true, presence: true,length: { in: 7..128, message: "パスワードは8文字以上128文字以下で入力してください" },on: :create
  validates :password_confirmation, presence: true,on: :create
  validates :family_name, presence: true
  validates :given_name, presence: true
  validates :family_name_kana, presence: true
  validates :given_name_kana, presence: true
  validates :phone, presence: true, format: {with: /\A[0-9]+\z/}

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.where(id: snscredential.user_id).first
      unless user.present? #ユーザーが存在しないなら
        user = User.new(
          # snsの情報
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential
    else #sns登録 未
      user = User.where(email: auth.info.email).first
      if user.present? #会員登録 済
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else #会員登録 未
        user = User.create(
          nickname: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider,
        )
      end
    end
    # hashでsnsのidを返り値として保持しておく
  return { user: user , sns_id: sns.id }
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    
  end

  def edit
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for :facebook
  end

  def google_oauth2
    callback_for :google
  end

  private

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # データベースに保存済みか確認
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      # 新規登録
      session["devise.sns_id"] = sns_id
      session[:password] = @user.password
      session[:password_confirmation] = @user.password
      session[:user_attributes] = @user
      # render "users/registrations/sns"
      redirect_to users_sign_up_sns_path
    end

    def failure
      # コールバックにエラーが起きた場合、リダイレクトします
      redirect_to root_path
    end

  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @years = Array.new((1900..2019).map{|y| [y,y]}.reverse)
  end

  def new_phone
    session[:nickname] = params[:user][:nickname]
    session[:email] = params[:user][:email]
    session[:password] = params[:user][:password]
    session[:password_confirmation] = params[:user][:password_confirmation]
    session[:family_name] = params[:user][:family_name]
    session[:given_name] = params[:user][:given_name]
    session[:family_name_kana] = params[:user][:family_name_kana]
    session[:given_name_kana] = params[:user][:given_name_kana]
    session[:birth_year] = params[:user][:birth_year]
    session[:birth_month] = params[:user][:birth_month]
    session[:birth_day] = params[:user][:birth_day]
    @user = User.new
  end

  def sns
    # sns先で使われている名前とメールアドレスをテキストボックスに入った状態をつくる
    @user = User.new(
      nickname:              session[:user_attributes]["nickname"],
      email:                 session[:user_attributes]["email"]
    )
    @years = Array.new((1900..2019).map{|y| [y,y]}.reverse)
  end
  
  def create
      @user = User.new(email:session[:email],password: session[:password], password_confirmation: session[:password_confirmation], phone: params[:user][:phone],nickname:session[:nickname],family_name: session[:family_name], given_name: session[:given_name], family_name_kana: session[:family_name_kana], given_name_kana: session[:given_name_kana], birth_year: session[:birth_year],birth_month: session[:birth_month],birth_day: session[:birth_day])
      if @user.save
        user = User.find_by(phone: params[:user][:phone])
        sns = SnsCredential.update(user_id: user.id)
        redirect_to new_address_users_path
        bypass_sign_in(@user)
      else
        redirect_to users_path
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone])
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :set_user
  # GET /resource/sign_in
  def new

  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private 
  def set_user
    @user = User.new
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end
  
  def new_address
    @user = User.find_by(id: current_user.id)
    @address = Address.new
    @prefectures = Prefecture.all
  end

  def create_address
    @address =Address.new(address_params)
    if @address.save
      redirect_to new_credit_credit_cards_path
    else
    end
  end

  def complete
    @users = User.new
  end

  private
  def address_params
    params.require(:address).permit(:user_id, :postal_code, :prefecture_id, :city, :block, :building, :phone)
  end

  def set_card
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.where(user_id: current_user.id).present?
  end

end

app/views/users/complete.html.haml
.complete-content
  .complete-content__mono-header
    = link_to root_path do
      =image_tag"logo.svg",class: 'complete-content__mono-header__logo'
  .complete-content__mono-header__situation
    .complete-content__mono-header__situation__bar
      .complete-content__mono-header__situation__bar__info 
        .complete-content__mono-header__situation__bar__info__text 会員情報
        .complete-content__mono-header__situation__bar__info__dot
        .complete-content__mono-header__situation__bar__info__line
      .complete-content__mono-header__situation__bar__tel
        .complete-content__mono-header__situation__bar__tel__text 電話番号認証
        .complete-content__mono-header__situation__bar__tel__dot
        .complete-content__mono-header__situation__bar__tel__line
      .complete-content__mono-header__situation__bar__address
        .complete-content__mono-header__situation__bar__address__text お届け先住所入力
        .complete-content__mono-header__situation__bar__address__dot
        .complete-content__mono-header__situation__bar__address__line
      .complete-content__mono-header__situation__bar__pay
        .complete-content__mono-header__situation__bar__pay__text 支払い方法
        .complete-content__mono-header__situation__bar__pay__dot
        .complete-content__mono-header__situation__bar__pay__line
      .complete-content__mono-header__situation__bar__finished 
        .complete-content__mono-header__situation__bar__finished__text 完了
        .complete-content__mono-header__situation__bar__finished__dot
        .complete-content__mono-header__situation__bar__finished__line
  .newinfo-content__mono-content
    .newinfo-content__mono-content__head 会員登録完了
    .newinfo-content__mono-content__space
      = form_for @users do |f|
        .field-first
          .thanks-text ありがとうございます。
          .thanks-text 会員登録が完了しました。
        .addressnext
          = link_to root_path,class:'next' do
            = f.submit "メルカリをはじめる",class:'next-btn'
= render 'shared/aaside'
= render 'shared/monofooter'

app/views/users/index.html.haml
= render 'shared/monoheader'
.mono-content
  .mono-content__selection
    .mono-content__selection__head 新規会員登録
    .mono-content__selection__space
      .mono-content__selection__space__content
        = link_to new_user_registration_path, data: {"turbolinks" => false},class:'mono-content__selection__space__content__mail' do
          = fa_icon "envelope-o",class:'mono-content__selection__space__content__mail__icon'
          .mono-content__selection__space__content__mail__text メールアドレスで登録する
        = link_to user_facebook_omniauth_authorize_path, method: :post,class:'mono-content__selection__space__content__facebook' do
          = fa_icon "facebook-square",class:'mono-content__selection__space__content__facebook__icon'
          .mono-content__selection__space__content__facebook__text Facebookで登録する
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post,class:'mono-content__selection__space__content__google' do
          = image_tag"google.svg",class:'mono-content__selection__space__content__google__icon'
          .mono-content__selection__space__content__google__text Googleで登録する
= render 'shared/monofooter'

app/views/users/new_address.html.haml
- content_for(:body_attributes) do
  data-turbolinks="false"
.newaddress-content
  .newaddress-content__mono-header
    = link_to root_path do
      =image_tag"logo.svg",class: 'newaddress-content__mono-header__logo'
  .newaddress-content__mono-header__situation
    .newaddress-content__mono-header__situation__bar
      .newaddress-content__mono-header__situation__bar__info 
        .newaddress-content__mono-header__situation__bar__info__text 会員情報
        .newaddress-content__mono-header__situation__bar__info__dot
        .newaddress-content__mono-header__situation__bar__info__line
      .newaddress-content__mono-header__situation__bar__tel
        .newaddress-content__mono-header__situation__bar__tel__text 電話番号認証
        .newaddress-content__mono-header__situation__bar__tel__dot
        .newaddress-content__mono-header__situation__bar__tel__line
      .newaddress-content__mono-header__situation__bar__address
        .newaddress-content__mono-header__situation__bar__address__text お届け先住所入力
        .newaddress-content__mono-header__situation__bar__address__dot
        .newaddress-content__mono-header__situation__bar__address__line
      .newaddress-content__mono-header__situation__bar__pay
        .newaddress-content__mono-header__situation__bar__pay__text 支払い方法
        .newaddress-content__mono-header__situation__bar__pay__dot
        .newaddress-content__mono-header__situation__bar__pay__line
      .newaddress-content__mono-header__situation__bar__finished 
        .newaddress-content__mono-header__situation__bar__finished__text 完了
        .newaddress-content__mono-header__situation__bar__finished__dot
        .newaddress-content__mono-header__situation__bar__finished__line
  .newinfo-content__mono-content
    .newinfo-content__mono-content__head お届け先住所入力
    .newinfo-content__mono-content__space
      = form_for @address,url:create_address_users_path, html: { id: :address_form } do |f|
        - if user_signed_in?
          .user
            = f.hidden_field :user_id, value: current_user.id
        .field-first
          = f.label :family_name,:given_name do
            お名前
            -# %span.required-icon
            -#   必須
          #textfield
            = current_user.family_name
          #textfield
            = current_user.given_name
        .addressfield
          = f.label :family_name_kana,:given_name_kana do
            お名前カナ
            -# %span.required-icon
            -#   必須
          #textfield
            = current_user.family_name_kana
          #textfield
            = current_user.given_name_kana
        .addressfield
          = f.label :postal_code do
            郵便番号
            %span.required-icon
              必須
          = f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "例) 123-4567",id:'textfield',class:'validate[required]'
        .field
          = f.label :prefecture_id do
            都道府県
            %span.required-icon
              必須
          = f.collection_select(:prefecture_id, @prefectures, :id, :name, {prompt: "--"},id:'textfield',class:'validate[required]')
        .field
          = f.label :city do
            市区町村
            %span.required-icon
              必須
          = f.text_field :city, autofocus: true, autocomplete: "city", placeholder: "例) 横浜市緑区",id:'textfield',class:'validate[required]'
        .field
          = f.label :block do
            番地
            %span.required-icon
              必須
          = f.text_field :block, autofocus: true, autocomplete: "block", placeholder: "例) 青山1-1-1",id:'textfield',class:'validate[required]'
        .field
          = f.label :building do
            建物名
            %span.option-icon
              任意
          = f.text_field :building, autofocus: true, autocomplete: "building", placeholder: "例) 柳ビル103",id:'textfield'
        .field
          = f.label :phone do
            電話
            %span.option-icon
              任意
          = f.text_field :phone, autofocus: true, autocomplete: "phone", placeholder: "例) 09012345678",id:'textfield'
        .addressnext
          = f.submit "次に進む",class:'next-btn'
= render 'shared/afooter'

-# = link_to new_credit_users_path,class:'next' do

app/views/users/new_phone.haml
.newphone-content
  .newphone-content__mono-header
    = link_to root_path do
      =image_tag"logo.svg",class: 'newphone-content__mono-header__logo'
    .newphone-content__mono-header__situation
      .newphone-content__mono-header__situation__bar
        .newphone-content__mono-header__situation__bar__info 
          .newphone-content__mono-header__situation__bar__info__text 会員情報
          .newphone-content__mono-header__situation__bar__info__dot
          .newphone-content__mono-header__situation__bar__info__line
        .newphone-content__mono-header__situation__bar__tel
          .newphone-content__mono-header__situation__bar__tel__text 電話番号認証
          .newphone-content__mono-header__situation__bar__tel__dot
          .newphone-content__mono-header__situation__bar__tel__line
        .newphone-content__mono-header__situation__bar__address
          .newphone-content__mono-header__situation__bar__address__text お届け先住所入力
          .newphone-content__mono-header__situation__bar__address__dot
          .newphone-content__mono-header__situation__bar__address__line
        .newphone-content__mono-header__situation__bar__pay
          .newphone-content__mono-header__situation__bar__pay__text 支払い方法
          .newphone-content__mono-header__situation__bar__pay__dot
          .newphone-content__mono-header__situation__bar__pay__line
        .newphone-content__mono-header__situation__bar__finished 
          .newphone-content__mono-header__situation__bar__finished__text 完了
          .newphone-content__mono-header__situation__bar__finished__dot
          .newphone-content__mono-header__situation__bar__finished__line
  .newphone-content__mono-content
    .newphone-content__mono-content__head 電話番号の確認
    .newphone-content__mono-content__space
      .newphone-content__mono-content__form
        = form_for @users do |f|
          .field
            = f.label :phone do
              携帯電話の番号
            %br/
            =f.text_field :phone,placeholder: "携帯電話の番号を入力",class:'input'
          .field
            .notice-text 本人確認のため、携帯番号のsms（ショートメッセージサービス）を利用して認証を行います。
          .next
            = link_to new_phone_users_path,class:'next' do
              = f.submit "smsを送信する",class:'next-btn'
          .field
            .notice-text ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
      .newphone-content__mono-content__space__notice 電話番号の確認が必要な理由＞
= render 'shared/afooter'