config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'  
  } 

  devise_scope :user do
    get 'users/sign_up/new_phone' => 'users/registrations#new_phone'
    get 'users/sign_up/sns' => 'users/registrations#sns'
    post 'users/sign_up/' => 'users/registrations#create'
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
  end

  # root画面
  root 'display_items#index'
  # ユーザー新規作成系のルーティング(※暫定！)
  resources :users do
    collection do
      get    :new_info #会員情報入力画面
      post   :create_info #処理
      get    :new_phone #電話番号入力画面
      post   :create_phone #処理
      get    :new_address #住所入力画面
      post   :create_address #処理
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
      get    :complete #完了画面
    end
  end
  # マイページのルーティング
  resources :mypages, only: [:index] do
    collection do
      get    :logout #ログアウト画面
      get    :display_items #出品中画面
      get    :trading_items #取引中画面
      get    :finished_items #売却済み画面
    end
  end
  # ニックネーム&紹介文の編集
  resources :user_nicknames, only: [:edit, :update]
  # 会員情報の編集
  resources :user_profiles, only: [:edit, :update]
  # クレジットカードの編集
  resources :credit_cards do
    collection do
      post 'buy'
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
    end
  end
  # 住所の編集
  resources :addresses,only: [:edit, :update]

  # 出品中-商品のルーティング
  resources :display_items do
    member do
      get :buy #購入画面
    end
    # コメントのルーティング(display_itemsとネスト)
    resources :comments, only: [:create, :destroy]
  end
  # 取引中-商品のルーティング
  resources :trading_items, only: [:create]
  # 出品停止中-商品のルーティング
  resources :stopping_items, only: [:create, :destroy]

  # イメージのルーティング
  resources :images, only: [:index] do
    collection do
      delete  :edit_destroy #編集ページの削除機能
    end
  end
  # カテゴリのルーティング
  resources :categories, only: [:index] do
    collection do
      post  :search_level1 #出品ページの検索、カテゴリ階層2
      post  :search_level2 #出品ページの検索、カテゴリ階層3
    end
  end
  # サイズのルーティング
  resources :sizes, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end
  # ブランドのルーティング
  resources :brands, only: [:index] do
    collection do
      post  :enter #ブランドボックスの作成チェック
      post  :search #出品ページの検索
    end
  end
  # 配送方法のルーティング
  resources :delivery_methods, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end

end

app/views/shared/_aaside.html.haml
%aside.main-aaside
  .main-aaside__background
    .main-aaside__background__phone
      .main-aaside__background__phone__download
        .main-aaside__background__phone__download__text1 \スマホでかんたんフリマアプリ/
        .main-aaside__background__phone__download__text2 今すぐに無料ダウンロード!
        .main-aaside__background__phone__download__text3
          =image_tag"app-store.svg",class: 'main-aaside__background__phone__download__text3__apple'
          =image_tag"google-play.svg",class: 'main-aaside__background__phone__download__text3__google'
      =image_tag"phone.png",class: 'main-aaside__background__phone__image'

app/views/shared/_afooter.html.haml
.a-footer
  .a-footer__content
    .a-footer__content__privacy
      .a-footer__content__privacy__text1 プライバシーポリシー
      .a-footer__content__privacy__text2 メルカリ利用規約
      .a-footer__content__privacy__text3 特定商取引に関する表記
    = link_to root_path do
      = image_tag"exhibit_logo_gray.svg",class: 'a-footer__content__logo'
    .a-footer__content__text © 2019 Mercari

app/views/shared/_aside.html.haml
%aside.main-aside
  .main-aside__background
    .main-aside__background__phone
      .main-aside__background__phone__download
        .main-aside__background__phone__download__text1 スマホでかんたんフリマアプリ
        .main-aside__background__phone__download__text2 今すぐに無料ダウンロード!
        .main-aside__background__phone__download__text3
          =image_tag"icon.png",class: 'main-aside__background__phone__download__text3__icon'
          =image_tag"app-store.svg",class: 'main-aside__background__phone__download__text3__apple'
          =image_tag"google-play.svg",class: 'main-aside__background__phone__download__text3__google'
      =image_tag"phone.png",class: 'main-aside__background__phone__image'

app/views/shared/_categories.html.haml
- @categories.each do |category|
  .main-content__items
    .main-content__items__title
      .main-content__items__title__text
        = category.name + "新着アイテム"
      .main-content__items__title__more 
        .main-content__items__title__more__text もっとみる
        =fa_icon "chevron-right",class: 'main-content__items__item__more__icon'     
    .main-content__items__item
      .main-content__items__item__content
        .main-content__items__item__content__box
          -# アイテムを描画
          - if category.name == "レディース"
            = render partial: "shared/items", locals: { display_items: @ladies }
          - elsif category.name == "メンズ"
            = render partial: "shared/items", locals: { display_items: @mens }
          - elsif category.name == "家電・スマホ・カメラ"
            = render partial: "shared/items", locals: { display_items: @electricals }
          - elsif category.name == "おもちゃ・ホビー・グッズ"
            = render partial: "shared/items", locals: { display_items: @hobies }

app/views/shared/_comment.html.haml
- num = 0
- @comments.each do |comment|
  - if num == 0
    %li.message__content__chat__box.chat__box__top.clearfix
      .message__content__chat__box__user
        .message__content__chat__box__user__frame
          = image_tag 'user-icon.svg', class: 'message__content__chat__box__user__frame__image'
          %span.message__content__chat__box__user__frame__name
            - if comment.user.nickname
              = comment.user.nickname
      .message__content__chat__box__comment
        .message__content__chat__box__comment__text
          = comment.comment
        .message__content__chat__box__comment__time
          = fa_icon "clock-o", class: "clock-icon"
          %span.message__content__chat__box__comment__time__ago
            = (@now - comment.created_at).seconds.ago.to_s(:human)
    - num += 1
  - else
    %li.message__content__chat__box.clearfix
      .message__content__chat__box__user
        .message__content__chat__box__user__frame
          = image_tag 'user-icon.svg', class: 'message__content__chat__box__user__frame__image'
          %span.message__content__chat__box__user__frame__name
            - if comment.user.nickname
              = comment.user.nickname
      .message__content__chat__box__comment
        .message__content__chat__box__comment__text
          = comment.comment
        .message__content__chat__box__comment__time
          = fa_icon "clock-o", class: "clock-icon"
          %span.message__content__chat__box__comment__time__ago
            = (@now - comment.created_at).seconds.ago.to_s(:human)

app/views/shared/_display_items.html.haml
- items.each do |item|
  .other-items__box__item-box
    = link_to "#", class: "other-items__box__item-box__link" do
      .other-items__box__item-box__frame
        = image_tag item.images[0].image.url, class: "other-items__box__item-box__frame__image"
      .other-items__box__item-box__detail
        %h3.other-items__box__item-box__detail__title
          = item.name
        .other-items__box__item-box__detail__footer
          .other-items__box__item-box__detail__footer__price
            = "¥" + item.price.to_s(:delimited)
          .other-items__box__item-box__detail__footer__like
            = fa_icon "heart-o", class: "heart-icon"
            %span 5

app/views/shared/_flash.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

app/views/shared/_footer.html.haml
%footer.main-footer
  .main-footer__information
    .main-footer__information__about
      .main-footer__information__about__title メルカリについて
      .main-footer__information__about__detail
        .main-footer__information__about__detail__company 会社概要（運営会社）
        .main-footer__information__about__detail__jobs 採用情報
        .main-footer__information__about__detail__news プレスリリース
        .main-footer__information__about__detail__blog 公式ブログ
        .main-footer__information__about__detail__guideline メルカリロゴ利用ガイドライン
        .main-footer__information__about__detail__sns
          =fa_icon "twitter",class: 'main-footer__information__about__detail__sns__twitter'
          =fa_icon "facebook-square",class: 'main-footer__information__about__detail__sns__facebook'
    .main-footer__information__help
      .main-footer__information__help__title ヘルプ＆ガイド
      .main-footer__information__help__detail
        .main-footer__information__help__detail__helpcenter メルカリガイド
        .main-footer__information__help__detail__rakuraku らくらくメルカリ便
        .main-footer__information__help__detail__yuyu ゆうゆうメルカリ便
        .main-footer__information__help__detail__rakurakubig 大型メルカリ便
        .main-footer__information__help__detail__car 車体取引ガイド
        .main-footer__information__help__detail__description メルカリあんしん・あんぜん宣言！
        .main-footer__information__help__detail__authenticity 偽ブランド品撲滅への取り組み
        .main-footer__information__help__detail__box メルカリボックス
    .main-footer__information__privacy
      .main-footer__information__privacy__title プライバシーと利用規約
      .main-footer__information__privacy__detail
        .main-footer__information__privacy__detail__leftside
          .main-footer__information__privacy__detail__leftside__privacy プライバシーポリシー
          .main-footer__information__privacy__detail__leftside__tos メルカリ利用規約
          .main-footer__information__privacy__detail__leftside__tosphone あんしんスマホサポート制度に関する利用特約
          .main-footer__information__privacy__detail__leftside__compliance コンプライアンスポリシー
        .main-footer__information__privacy__detail__rightside
          .main-footer__information__privacy__detail__rightside__data 個人データの安全管理に係る基本方針
          .main-footer__information__privacy__detail__rightside__tokutei 特定商取引に関する表記
          .main-footer__information__privacy__detail__rightside__kessai 資金決済法に基づく表示
          .main-footer__information__privacy__detail__rightside__safety 法令順守と犯罪抑止のために
    .main-footer__information__countries
      .main-footer__information__countries__title 国
      .main-footer__information__countries__detail
        .main-footer__information__countries__detail__jp 日本
        .main-footer__information__countries__detail__us United States
  .main-footer__copyright
    =image_tag"logoBW.svg",class: 'main-footer__copyright__image'
    .main-footer__copyright__text © 2019 Mercari

app/views/shared/_header.html.haml
%header.main-header
  .main-header__content
    .main-header__content__upper
      .main-header__content__upper__logo
        = link_to root_path do
          =image_tag"logo.png",size: "134x36",class: 'logo'
      .main-header__content__upper__form
        %input.main-header__content__upper__form__search{placeholder: "何かお探しですか？"}
          %button.main-header__content__upper__form__search-btn
        -# = form_for @display_item do |f|
        -#   = f.text_field :price, placeholder: "何かお探しですか？",class: "main-header__content__upper__form__search"
        -#   = f.button "",class: "main-header__content__upper__form__search-btn"

    .main-header__content__lower
      .main-header__content__lower__leftside
        .main-header__content__lower__leftside__category
          =fa_icon "list-ul",class: 'main-header__content__lower__leftside__category__icon'
          .main-header__content__lower__leftside__category__text カテゴリーから探す
        .main-header__content__lower__leftside__brand
          =fa_icon "tags",class: 'main-header__content__lower__leftside__brand__icon'
          .main-header__content__lower__leftside__brand__text ブランドから探す

      .main-header__content__lower__rightside
        - if user_signed_in?
          .main-header__content__lower__rightside__like
            =fa_icon "heart-o",class: 'main-header__content__lower__rightside__like__icon'
            .main-header__content__lower__rightside__like__text いいね！一覧
          .main-header__content__lower__rightside__notice
            =fa_icon "bell-o",class: 'main-header__content__lower__rightside__notice__icon'
            .main-header__content__lower__rightside__notice__text お知らせ
          .main-header__content__lower__rightside__todolist
            =fa_icon "check",class: 'main-header__content__lower__rightside__todolist__icon'
            .main-header__content__lower__rightside__todolist__text やることリスト
          .main-header__content__lower__rightside__mypage
            =image_tag "mypage.png",class: 'main-header__content__lower__rightside__mypage__icon'
            = link_to mypages_path, data: {turbolinks: :false}, class: ".main-header__content__lower__rightside__mypage__text" do
              マイページ
        - else
          .main-header__content__lower__rightside__new
            = link_to users_path, class: ".main-header__content__lower__rightside__new__link" do
              .main-header__content__lower__rightside__new__text
                新規会員登録
          .main-header__content__lower__rightside__login
            = link_to new_user_session_path, class: ".main-header__content__lower__rightside__login__link" do
              .main-header__content__lower__rightside__login__text
                ログイン

app/views/shared/_items.html.haml
- display_items.each do |display_item|
  = link_to display_item_path(display_item[:id]), data:{turbolinks: "false"} do
    .main-content__items__item__content__box__2
      // 売り切れアイコン
      - if display_item.trading_item
        .main-content__items__item__content__box__2__soldout-box
        .main-content__items__item__content__box__2__soldout-text
          SOLD
      .main-content__items__item__content__box__2__frame
        = image_tag display_item.images[0].image.url, class: "main-content__items__item__content__box__2__frame__image"
        // 上記のパスでとりあえず画像が出せます！
        .main-content__items__item__content__box__2__frame__price
          %span
            = "¥" + display_item.price.to_s(:delimited)
      .main-content__items__item__content__box__2__items-name
        %span
          = display_item.name

app/views/shared/_monofooter.html.haml
.mono-footer
  .mono-footer__content
    .mono-footer__content__privacy
      .mono-footer__content__privacy__text1 プライバシーポリシー
      .mono-footer__content__privacy__text2 メルカリ利用規約
      .mono-footer__content__privacy__text3 特定商取引に関する表記
    = link_to root_path do
      = image_tag"exhibit_logo_gray.svg",class: 'mono-footer__content__logo'
    .mono-footer__content__text © 2019 Mercari

app/views/shared/_monoheader.html.haml
.mono-header
  .mono-header__logo
    = link_to root_path do
      =image_tag"logo.svg",class: 'mono-header__logo__image'

app/views/shared/_sell-icon.html.haml
.sell-icon 
  = link_to new_display_item_path, class: ".sell-icon__text", data:{turbolinks: "false"} do
    .sell-icon__text 出品
    =fa_icon "camera",class: 'sell-icon__image'

app/views/shared/_side-bar.html.haml
.mypage__side-bar
  %nav
    %ul.mypage__side-bar__list
      %li
        = link_to mypages_path, class: "mypage__side-bar__list-item" do
          マイページ
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          お知らせ
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          やることリスト
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          いいね！一覧
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to new_display_item_path, class: "mypage__side-bar__list-item" do
          出品する
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to display_items_mypages_path, class: "mypage__side-bar__list-item" do
          出品した商品-出品中
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to trading_items_mypages_path, class: "mypage__side-bar__list-item" do
          出品した商品-取引中
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to finished_items_mypages_path, class: "mypage__side-bar__list-item" do
          出品した商品-売却済み
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          購入した商品-取引中
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          購入した商品-過去の取引
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          ニュース一覧
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          評価一覧
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          ガイド
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          お問い合わせ
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
    %h3.mypage__side-bar__head
      メルペイ
    %ul.mypage__side-bar__list
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          売上・振込申請
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          ポイント
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
  .mypage__side-bar__config
    %h3.mypage__side-bar__head
      設定
    %ul.mypage__side-bar__list
      %li
        = link_to edit_user_nickname_path(current_user.id), class: "mypage__side-bar__list-item" do
          プロフィール
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          発送元・お届け先住所変更
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        - if current_user.credit_card.present?
          = link_to credit_card_path(current_user.credit_card.id), class: "mypage__side-bar__list-item" do
            支払い方法
            = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
        - else
          = link_to credit_cards_path, class: "mypage__side-bar__list-item" do
            支払い方法
            = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          メール/パスワード
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to edit_address_path(current_user.id), class: "mypage__side-bar__list-item" do
          本人情報
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to "#", class: "mypage__side-bar__list-item" do
          電話番号の確認
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"
      %li
        = link_to logout_mypages_path, class: "mypage__side-bar__list-item" do
          ログアウト
          = fa_icon 'fas fa-angle-right', class: "fa-angle-right fa-pull-right"