config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'  
  } 

  devise_scope :user do
    get 'users/sign_up/new_phone' => 'users/registrations#new_phone'
    get 'users/sign_up/sns' => 'users/registrations#sns'
    post 'users/sign_up/' => 'users/registrations#create'
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
  end

  # root画面
  root 'display_items#index'
  # ユーザー新規作成系のルーティング(※暫定！)
  resources :users do
    collection do
      get    :new_info #会員情報入力画面
      post   :create_info #処理
      get    :new_phone #電話番号入力画面
      post   :create_phone #処理
      get    :new_address #住所入力画面
      post   :create_address #処理
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
      get    :complete #完了画面
    end
  end
  # マイページのルーティング
  resources :mypages, only: [:index] do
    collection do
      get    :logout #ログアウト画面
      get    :display_items #出品中画面
      get    :trading_items #取引中画面
      get    :finished_items #売却済み画面
    end
  end
  # ニックネーム&紹介文の編集
  resources :user_nicknames, only: [:edit, :update]
  # 会員情報の編集
  resources :user_profiles, only: [:edit, :update]
  # クレジットカードの編集
  resources :credit_cards do
    collection do
      post 'buy'
      get    :new_credit #クレカ入力画面
      post   :create_credit #処理
    end
  end
  # 住所の編集
  resources :addresses,only: [:edit, :update]

  # 出品中-商品のルーティング
  resources :display_items do
    member do
      get :buy #購入画面
    end
    # コメントのルーティング(display_itemsとネスト)
    resources :comments, only: [:create, :destroy]
  end
  # 取引中-商品のルーティング
  resources :trading_items, only: [:create]
  # 出品停止中-商品のルーティング
  resources :stopping_items, only: [:create, :destroy]

  # イメージのルーティング
  resources :images, only: [:index] do
    collection do
      delete  :edit_destroy #編集ページの削除機能
    end
  end
  # カテゴリのルーティング
  resources :categories, only: [:index] do
    collection do
      post  :search_level1 #出品ページの検索、カテゴリ階層2
      post  :search_level2 #出品ページの検索、カテゴリ階層3
    end
  end
  # サイズのルーティング
  resources :sizes, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end
  # ブランドのルーティング
  resources :brands, only: [:index] do
    collection do
      post  :enter #ブランドボックスの作成チェック
      post  :search #出品ページの検索
    end
  end
  # 配送方法のルーティング
  resources :delivery_methods, only: [:index] do
    collection do
      post  :search #出品ページの検索
    end
  end

end

app/models/display_item.rb
class DisplayItem < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # バリデーション
  validates :name,          presence: true
  validates :name,          length: { in: 1..40 }
  validates :description,   presence: true
  validates :description,   length: { in: 1..1000 }
  validates :category_id,   presence: true
  validates :size_id,       presence: true, if: :category_has_size?
  validates :condition_id,  presence: true
  validates :delivery_fee_burden_id,  presence: true
  validates :delivery_method_id,  presence: true
  validates :prefecture_id,  presence: true
  validates :delivery_by_day_id,  presence: true
  validates :price,         numericality: {only_integer: true, greater_than: 299, less_than: 10000000}
  validates_associated :images

  belongs_to_active_hash :condition
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_fee_burden
  belongs_to_active_hash :delivery_method
  belongs_to_active_hash :delivery_by_day

  belongs_to :user
  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :brand, optional: true

  has_many :images, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  has_one :trading_item, dependent: :destroy
  has_one :finished_item, dependent: :destroy
  has_one :stopping_item, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true

  def category_has_size?
    if category_id
      Category.find(category_id).size_id != nil
    end
  end

  def previous
    DisplayItem.where("id < ?", self.id).order("id DESC").first
  end

  def next
    DisplayItem.where("id > ?", self.id).order("id ASC").first
  end
end

app/controllers/display_items_controller.rb
class DisplayItemsController < ApplicationController
  before_action :find_display_item, only: [:show, :destroy, :edit]

  require "date"

  def index
    # カテゴリーを取得
    @lady = Category.find_by(name: "レディース")
    @man = Category.find_by(name: "メンズ")
    @electrical = Category.find_by(name: "家電・スマホ・カメラ")
    @hobby = Category.find_by(name: "おもちゃ・ホビー・グッズ")
 
    # カテゴリをまとめて配列に保存
    @categories = [@lady, @man, @electrical, @hobby]

    @items = DisplayItem.order('created_at DESC')
    @ladies = []
    @mens = []
    @electricals = []
    @hobies = []

    @items.each do |item|
      if item.stopping_item.nil? && 
        if item.category.parent.parent_id == @lady.id && @ladies.length < 10
          @ladies << item
        elsif item.category.parent.parent_id == @man.id && @mens.length < 10
          @mens << item
        elsif item.category.parent.parent_id == @electrical.id && @electricals.length < 10
          @electricals << item
        elsif item.category.parent.parent_id == @hobby.id && @hobies.length < 10
          @hobies << item
        elsif @ladies == 10 && @mens == 10 && @electricals == 10 && @hobies == 10
          break
        end
      end
    end


  end

  def new
    @display_item = DisplayItem.new
    @display_item.images.build
    # セレクトボックスの中身を取得
    get_select_box_contents
  end

  def create
    @display_item = DisplayItem.new(display_item_params)
    # イメージが存在しない時は登録させない
    if display_item_params[:images_attributes] && @display_item.save
      redirect_to root_path, notice: '商品を出品しました'
    else
      # セレクトボックスの中身を取得
      get_select_box_contents
      # newページに戻す
      render action: :new
    end
  end

  def show
    # show用の変数取得
    get_show_variables
    # 必ず最後に入れる
    render :layout => 'display_items_show'
  end

  def edit
    @images = @display_item.images
    # セレクトボックスの中身を取得
    get_select_box_contents
    # edit用の初期情報を取得
    get_edit_variables
  end

  def update
    @display_item = DisplayItem.find(params[:id])
    if @display_item.update(display_item_params)
      redirect_to display_item_path(params[:id]), notice: '商品を編集しました'
    else
      redirect_to edit_display_item_path(params[:id]), alert: '編集に失敗しました'
    end
  end

  def destroy
    if @display_item.destroy
      redirect_to display_items_mypages_path, notice: '商品を削除しました'
    end
  end

  def buy
    @display_item = DisplayItem.find(params[:id])
    @trading_item = TradingItem.new
  end



  private

  def display_item_params
    # brand_idが名前で入っているためidに変換、見つからない時はnullを入れる
    if Brand.find_by(name: params[:display_item][:brand_id])
      params[:display_item][:brand_id] = Brand.find_by(name: params[:display_item][:brand_id]).id
    else
      params[:display_item][:brand_id] = nil
    end
    # size_idがないときは、nullで入力する
    unless params[:display_item][:size_id]
      params[:display_item][:size_id] = nil
    end
    params.require(:display_item).permit(:user_id, :name, :description, :category_id, :size_id, :brand_id, :condition_id, :delivery_fee_burden_id, :delivery_method_id, :prefecture_id, :delivery_by_day_id, :price, images_attributes: [:image, :id, :_destroy])
  end

  def find_display_item
    @display_item = DisplayItem.find(params[:id])
  end

  def get_select_box_contents
    @categories = Category.where(ancestry: nil)
    @sizes = Size.where(ancestry: nil)
    @brands = Brand.all
    @conditions = Condition.all
    @delivery_fee_burdens = DeliveryFeeBurden.all
    @delivery_methods = DeliveryMethod.all
    @prefectures = Prefecture.all
    @delivery_by_days = DeliveryByDay.all
  end

  def get_show_variables
    # カテゴリ系
    @category_lv1 = @display_item.category
    @category_lv2 = @category_lv1.parent
    @category_lv3 = @category_lv2.parent if @category_lv2.parent
    # コメント生成
    @comment = Comment.new
    # コメントを取得、コメント時間算出用の時間取得
    @comments = @display_item.comments
    @now = Time.now
    # 次のアイテム、前のアイテム取得
    @mine_items = DisplayItem.where(user_id: @display_item[:user_id])
    @same_category_items = DisplayItem.where(category_id: @display_item[:category_id])
  end

  def get_edit_variables
    # カテゴリー
    if @display_item.category.parent.parent
      @category_lv1_id = @display_item.category.parent.parent.id
      @category_lv2_id = @display_item.category.parent.id
      @category_lv3_id = @display_item.category_id

      @category_lv2_group = @display_item.category.parent.parent.children
      @category_lv3_group = @display_item.category.parent.children
    else
      @category_lv1_id = @display_item.category.parent.id
      @category_lv2_id = @display_item.category_id

      @category_lv2_group = @display_item.category.parent.children
    end
    # サイズ
    if @display_item.size
      @size_id = @display_item.size_id
      @size_groups = @display_item.size.parent.children
    end
    # ブランド
    if @display_item.brand
      @brand_name = @display_item.brand.name
    end
    # 配送方法
    if @display_item.delivery_fee_burden_id == 1
      @delivery_methods = DeliveryMethod.where(type: 3)
    else
      @delivery_methods = DeliveryMethod.where(type: 1)
    end
  end

end

app/views/display_items/buy.html.haml
.exhibit
  .exhibit__header
    .exhibit__header__logo
      = link_to root_path do
        = image_tag "exhibit_logo.svg"

  = form_for @trading_item ,url: buy_credit_cards_path do |f|
    = f.hidden_field :display_item_id, value: @display_item.id
    = f.hidden_field :user_id, value: current_user.id
    %input{:name => "payjp-token", :type => "hidden", :value => "tok_...."}/
    .exhibit__main
      .exhibit__main__box
        %h2.exhibit__main__box__title
          購入内容の確認
      .content
        .content__inner__top
          =image_tag @display_item.images[0].image.url ,class:'display_item_image'
          %span.word 
            = @display_item.name
            
        .content__inner
          .content__inner__price
            %p5
              = "¥" + @display_item.price.to_s(:delimited)
            %span.item-shipping-fee 送料込み
          .content__inner
            .content__inner__point
              ポイントはありません
          .pay
            .pay__payment
              支払い金額
            .pay__payment__right 
              %span.price
              =  "¥" + @display_item.price.to_s(:delimited)
          -if current_user.credit_card && current_user.address
            .content__inner
              = f.submit({value: "購入する", class: "buy-btn"})
          -else
            .error
              配送先と支払い方法の入力を完了てください。
            .content__inner
              = f.submit({value: "購入する", class: "payment-btn"})


    .content
      .content__inner
        %h3.content__inner__text
        配送先
        %address
          = "〒-" + current_user.address&.postal_code.to_s
        %p
          = current_user.address&.prefecture&.name
          = current_user.address&.city
          = current_user.address&.block
          = current_user.address&.building
        %p
          = current_user&.family_name
          = current_user&.given_name
        = link_to edit_address_path, class: "change" do
          変更する
          =fa_icon "chevron-right"
    .content
      -if current_user.credit_card.nil?
        .content__inner
          %h3.content__inner__text
          支払い方法
          %br /
          = link_to new_credit_card_path, class: "change" ,data:{turbolinks:"false"} do
            変更する
            =fa_icon "chevron-right"
      -else 
        .content__inner
          %h3.content__inner__text
          支払い方法
          visa
          = link_to new_credit_card_path, class: "change" do
            変更する
            =fa_icon "chevron-right"

  .exhibit__footer
    .exhibit__footer__navi
      %ul.exhibit__footer__navi__list
        %li
          = link_to "#", class: "exhibit__footer__navi__list__ele" do
            プライバシーポリシー
        %li
          = link_to "#", class: "exhibit__footer__navi__list__ele" do
            メルカリ利用規約
        %li
          = link_to "#", class: "exhibit__footer__navi__list__ele" do
            特定商取引に関する表記
    .exhibit__footer__logo
      = link_to root_path do
        = image_tag "exhibit_logo_gray.svg"

    .exhibit__footer__copylight
      %p.exhibit__footer__copylight__text
        © 2019 Mercari

app/views/display_items/index.html.haml
%header.main-header1
  .main-header__content
    .main-header__content__upper
      .main-header__content__upper__logo
        = link_to root_path do
          =image_tag"logo.png",size: "134x36",class: 'logo'
      .main-header__content__upper__form
        %input.main-header__content__upper__form__search{placeholder: "何かお探しですか？"}
          %button.main-header__content__upper__form__search-btn
        -# = form_for @display_item do |f|
        -#   = f.text_field :price, placeholder: "何かお探しですか？",class: "main-header__content__upper__form__search"
        -#   = f.button "",class: "main-header__content__upper__form__search-btn"

    .main-header__content__lower
      .main-header__content__lower__leftside
        .main-header__content__lower__leftside__category
          =fa_icon "list-ul",class: 'main-header__content__lower__leftside__category__icon'
          .main-header__content__lower__leftside__category__text カテゴリーから探す
        .main-header__content__lower__leftside__brand
          =fa_icon "tags",class: 'main-header__content__lower__leftside__brand__icon'
          .main-header__content__lower__leftside__brand__text ブランドから探す

      .main-header__content__lower__rightside
        - if user_signed_in?
          .main-header__content__lower__rightside__like
            =fa_icon "heart-o",class: 'main-header__content__lower__rightside__like__icon'
            .main-header__content__lower__rightside__like__text いいね！一覧
          .main-header__content__lower__rightside__notice
            =fa_icon "bell-o",class: 'main-header__content__lower__rightside__notice__icon'
            .main-header__content__lower__rightside__notice__text お知らせ
          .main-header__content__lower__rightside__todolist
            =fa_icon "check",class: 'main-header__content__lower__rightside__todolist__icon'
            .main-header__content__lower__rightside__todolist__text やることリスト
          .main-header__content__lower__rightside__mypage
            =image_tag "mypage.png",class: 'main-header__content__lower__rightside__mypage__icon'
            = link_to mypages_path, data: {turbolinks: :false}, class: ".main-header__content__lower__rightside__mypage__text" do
              マイページ
        - else
          .main-header__content__lower__rightside__new
            = link_to users_path, class: ".main-header__content__lower__rightside__new__link" do
              .main-header__content__lower__rightside__new__text
                新規会員登録
          .main-header__content__lower__rightside__login
            = link_to new_user_session_path, class: ".main-header__content__lower__rightside__login__link" do
              .main-header__content__lower__rightside__login__text
                ログイン
= render 'shared/flash'
.main-content
  .slider
    .slide1
      =image_tag "slide-1.png",class:'image-1'
    .slide2
      .slide2-content
        .slide2-content__text
          .slide2-content__text__text1 スマホで かんたん
          .slide2-content__text__text2 フリマアプリ
          .slide2-content__text__text3 メルカリはスマホカメラからすぐに出品できる
          .slide2-content__text__text4 購入時も安心な独自システムのアプリです
          .slide2-content__text__app
            =image_tag"app-store.svg",class: 'slide2-content__text__app__apple'
            =image_tag"google-play.svg",class: 'slide2-content__text__app__google'
        =image_tag "slidephone.png",class:'image-4'
    .slide3
      =image_tag "slide-3.png",class:'image-1'

  .main-content__itemslist
    .main-content__itemslist__text
      人気のカテゴリー
    %ul.main-content__itemslist__text__categories
      %li.main-content__itemslist__text__categories__list
        レディース
      %li.main-content__itemslist__text__categories__list
        メンズ
      %li.main-content__itemslist__text__categories__list
        家電・スマホ・カメラ
      %li.main-content__itemslist__text__categories__list
        おもちゃ・ホビー・グッズ

    .main-content__itemslist__tagspace
      .main-content__itemslist__tagspace__tag
        -# .main-content__itemslist__tagspace__tag__1 エンジニア
        -# .main-content__itemslist__tagspace__tag__2 人
        -# .main-content__itemslist__tagspace__tag__3 Ruby
        -# .main-content__itemslist__tagspace__tag__4 JS

  -# カテゴリを複数表示
  = render "shared/categories"

= render 'shared/sell-icon'
= render 'shared/aside'
= render 'shared/footer'

app/views/display_items/show.html.haml
= render 'shared/header'
= render 'shared/flash'

.item

  .item__title
    = @display_item.name

  .item__content.clearfix
    // 売切アイコン
    .item__content__photo
      - if @display_item.trading_item
        .item__content__photo__soldout-box
        .item__content__photo__soldout-text
          SOLD
      // 本体
      %ul.item__content__photo__slider
        -# 画像の個数分だけ描画
        - @display_item.images.each do |image|
          %li.slide-item
            = image_tag image.image.url
      // サムネ
      %ul.item__content__photo__thumb
        -# 画像の個数分だけ描画
        - @display_item.images.each do |image|
          %li.thumbnail-item
            = image_tag image.image.url


    %table.item__content__table
      %tbody.item__content__table__tbody

        %tr.item__content__table__tr
          %th.item__content__table__th
            出品者
          %td.item__content__table__td
            = link_to "#" do
              = @display_item.user.nickname
            .item__content__table__box
              .item__content__table__box__icon
                = fa_icon "smile-o", class: "nice-icon red"
                %span.item__content__table__box__value
                  99
              .item__content__table__box__icon
                = fa_icon "meh-o", class: "nice-icon yellow"
                %span.item__content__table__box__value
                  99
              .item__content__table__box__icon
                = fa_icon "frown-o", class: "nice-icon blue"
                %span.item__content__table__box__value
                  99

        %tr.item__content__table__tr
          %th.item__content__table__th
            カテゴリー
          %td.item__content__table__td
            .icon_box
              = link_to "#", class: "item__content__table__td__link" do
                %span
                  - if @category_lv3.nil?
                    = @category_lv2.name
                  - else
                    = @category_lv3.name
            .icon_box
              = link_to "#", class: "item__content__table__td__link" do
                = fa_icon "chevron-right"
                %span
                  - if @category_lv3.nil?
                    = @category_lv1.name
                  - else
                    = @category_lv2.name
            - unless @category_lv3.nil?
              .icon_box
                = link_to "#", class: "item__content__table__td__link" do
                  = fa_icon "chevron-right"
                  %span
                    = @category_lv1.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            ブランド
          %td.item__content__table__td
            - unless @display_item.brand_id.nil? 
              = @display_item.brand.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            商品のサイズ
          %td.item__content__table__td
            - unless @display_item.size_id.nil? 
              =  @display_item.size.size

        %tr.item__content__table__tr
          %th.item__content__table__th
            商品の状態
          %td.item__content__table__td
            = @display_item.condition.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            配送料の負担
          %td.item__content__table__td
            = @display_item.delivery_fee_burden.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            配送の方法
          %td.item__content__table__td
            = @display_item.delivery_method.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            配送元地域
          %td.item__content__table__td
            = link_to "#", class: "item__content__table__td__link" do
              = @display_item.prefecture.name

        %tr.item__content__table__tr
          %th.item__content__table__th
            配送日の目安
          %td.item__content__table__td
            = @display_item.delivery_by_day.name


  .item__fee
    %span.item__fee__price
      = "¥" + @display_item.price.to_s(:delimited)
    %span.item__fee__tax (税込)
    %span.item__fee__option 送料込み
  // 既に買われていないかチェック
  - if user_signed_in?
    - if @display_item.trading_item
      // 他人が出品した商品で表示する
      - if @display_item.user_id != current_user.id
        .item__btn
          %span.item__btn__impossible
            売り切れました
    - else
      - if @display_item.user_id != current_user.id
        .item__btn
          = link_to buy_display_item_path(@display_item.id), class: "item__btn__possible", data:{turbolinks: "false"} do
            購入画面に進む


  .item__description
    %p.item__description__text
      = @display_item.description

  // 他人が出品した商品で表示する
  - if user_signed_in?
    - if @display_item.user_id != current_user.id
      .item__footer.clearfix
        .item__footer__left
          %span.item__footer__left__like
            = fa_icon "heart-o", class: "like-icon"
            %span.item__footer__left__like__text
              いいね!
            %spna.item__footer__left__like__count
              100
          = link_to "#", class: "item__footer__left__report" do
            = fa_icon "flag-o", class: "report-icon"
            %span.item__footer__left__report__text
              不適切な商品の報告

    .item__footer__right
      = link_to "#", class: "item__footer__right__safe" do
        = fa_icon "lock", class: "lock-icon"
        %span.item__footer__right__safe__text
          あんしん・あんぜんへの取り組み
- if user_signed_in?
  - if @display_item.user_id == current_user.id
    .item-change
      = link_to edit_display_item_path(@display_item.id), class: "item-change__edit", data:{turbolinks: "false"} do
        商品の編集
      %p or
      - if @display_item.stopping_item
        = link_to stopping_item_path(@display_item.id), method: :delete, data: { confirm: '出品を再開しますか？', turbolinks: "false" }, class: "item-change__restart" do
          出品を再開する
      - else
        = link_to stopping_items_path(@display_item.id), method: :post, data: { confirm: '出品を停止しますか？', turbolinks: "false" }, class: "item-change__stop" do
          出品を一旦停止する
      = link_to display_item_path(@display_item.id), method: :delete, data: { confirm: '削除しますか？', turbolinks: "false" }, class: "item-change__delete" do
        この商品を削除する

.message
  .message__content
    .message__content__chat
      %ul
        = render "./shared/comment"

    .message__content__form
      = form_for [@display_item, @comment] do |f|
        %p.message__content__form__notes
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        -# user_idとdisplay_item_id取得
        - if user_signed_in?
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :display_item_id, value: @display_item.id
        - if @display_item.trading_item
          = f.text_area :comment, class: "message__content__form__text-field", disabled: true
          = f.submit "売り切れのためコメントできません", class: "message__content__form__submit-impossible", disabled: true
        - else
          = f.text_area :comment, class: "message__content__form__text-field"
          = f.submit "コメントする", class: "message__content__form__submit"
// 他人が出品した商品で表示する
- if user_signed_in?
  - if @display_item.user_id != current_user.id
    %ul.navi-link.clearfix
      - if @display_item.previous.present?
        %li.navi-link__prev
          = link_to display_item_path(@display_item.previous.id), class: "navi-link__link" do
            = fa_icon "angle-left", class: "icon icon__prev"
            %span
              = @display_item.previous.name
      - if @display_item.next.present?
        %li.navi-link__next
          = link_to display_item_path(@display_item.next.id), class: "navi-link__link" do
            %span
              = @display_item.next.name
            = fa_icon "angle-right", class: "icon icon__next"
- if user_signed_in?
  // 他人が出品した商品で表示する
  - if @display_item.user_id != current_user.id
    .media
      .media_text
      %ul.media__box
        %li.media__box__ele
          = link_to "#" do
            %span.media__box__ele__box.media-facebook
              = fa_icon "facebook-official", class: "media-icon"
        %li.media__box__ele
          = link_to "#" do
            %span.media__box__ele__box.media-twitter
              = fa_icon "twitter", class: "media-icon"
        %li.media__box__ele
          = link_to "#" do
            %span.media__box__ele__box.media-pinterest
              = fa_icon "pinterest ", class: "media-icon"
- if user_signed_in?
  // 他人が出品した商品で表示する
  - if @display_item.user_id != current_user.id
    .other-items.clearfix
      - unless @mine_items.length == 0
        .other-items__top-box
          %h2.other-items__name
            = link_to "a", class: "other-items__name__link" do
              = @display_item.user.nickname + "さんのその他の出品"
          .other-items__box.clearfix
            = render partial: "./shared/display_items", locals: {items: @mine_items}

      - unless @same_category_items.length == 0
        .other-items__bottom-box
          %h2.other-items__name
            = link_to "a", class: "other-items__name__link" do
              - if @category_lv3
                = @category_lv1.name + "（#{@category_lv3.name}）その他の商品"
              - else
                = @category_lv1.name + "（#{@category_lv2.name}）その他の商品"
          .other-items__box.clearfix
            = render partial: "./shared/display_items", locals: {items: @same_category_items}
- if user_signed_in?
  // 他人が出品した商品で表示する
  - if @display_item.user_id != current_user.id
    .navi
      %ul.navi__box
        %li.navi__box__list
          = link_to root_path, class: "navi__box__list__link" do
            メルカリ
          = fa_icon "chevron-right"
        %li.navi__box__list
          %span.navi__box__list__link-right
            = @display_item.name

= render 'shared/aside'
= render 'shared/footer'